apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client-deployment
  namespace: singlebranch  # Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-client
  template:
    metadata:
      labels:
        app: java-client
    spec:
      containers:
      - name: java-client
        image: romeo23/client-repo-jenkins:latest
        env:
          - name: SERVER_SERVICE_NAME
            value: "java-server-service.singlebranch.svc.cluster.local"  # Updated for singlebranch namespace
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        stdin: true  # Enable stdin for interactive input
        tty: true    # Enable tty for terminal interaction
        volumeMounts:
          - name: log-volume
            mountPath: /app/logs
      volumes:
        - name: log-volume
          hostPath:
            path: /var/logs/client  # Adjust this path as needed
