apiVersion: v1
kind: Service
metadata:
  name: java-client-service
  namespace: singlebranch  # Specify the namespace here
spec:
  selector:
    app: java-client
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

